SELECT
    B.AUTHOR_ID,
    AUTHOR_NAME,
    CATEGORY,
    SUM(SALES*PRICE) AS TOTAL_SALES 
FROM BOOK B
LEFT JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
LEFT JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
GROUP BY B.AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY B.AUTHOR_ID, CATEGORY DESC