SELECT YEAR(B.SALES_DATE) as YEAR, 
        MONTH(B.SALES_DATE) as MONTH, 
        A.GENDER as GENDER, 
        COUNT(distinct A.user_id) as USERS
FROM USER_INFO A JOIN ONLINE_SALE B
ON A.USER_ID = B.USER_ID
WHERE gender IS NOT NULL
GROUP BY 1, 2, 3
ORDER BY 1, 2, 3;