-- 코드를 입력하세요
SELECT CAR_ID, CAR_TYPE, FEE
FROM (
    SELECT 
        C.CAR_ID, 
        C.CAR_TYPE, 
        ROUND(30*DAILY_FEE*((1-DISCOUNT_RATE/100))) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D ON C.CAR_TYPE = D.CAR_TYPE  AND D.DURATION_TYPE = '30일 이상'
    WHERE C.CAR_TYPE IN ('세단', 'SUV')
    AND C.CAR_ID NOT IN (
          SELECT R.CAR_ID
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY R
          WHERE R.START_DATE <= DATE '2022-11-30'
            AND R.END_DATE >= DATE '2022-11-01'
      )
) A
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;
