WITH HEAVY AS (
    SELECT HOST_ID, COUNT(HOST_ID) CNT
    FROM PLACES
    GROUP BY HOST_ID)

SELECT PLACES.*
FROM PLACES, HEAVY
WHERE PLACES.HOST_ID IN HEAVY.HOST_ID
AND HEAVY.CNT > 1
ORDER BY ID ASC