SELECT
    HISTORY_ID,
    CASE
        WHEN PERIOD >= 90 
        THEN DAILY_FEE*PERIOD*((100-(SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = A.CAR_TYPE AND DURATION_TYPE = '90일 이상'))/100)
        WHEN PERIOD >= 30
        THEN DAILY_FEE*PERIOD*((100-(SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = A.CAR_TYPE AND DURATION_TYPE = '30일 이상'))/100)
        WHEN PERIOD >= 7 
        THEN DAILY_FEE*PERIOD*((100-(SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = A.CAR_TYPE AND DURATION_TYPE = '7일 이상'))/100)
    ELSE DAILY_FEE*PERIOD
    END AS FEE
FROM (
    SELECT 
        R.HISTORY_ID,
        C.CAR_ID, 
        C.CAR_TYPE,
        C.DAILY_FEE,
        (R.END_DATE-R.START_DATE+1) AS PERIOD
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY R ON C.CAR_ID = R.CAR_ID AND C.CAR_TYPE = '트럭'
) A 
ORDER BY FEE DESC, HISTORY_ID DESC