SELECT 
    FLAVOR
FROM (
    SELECT 
        ROWNUM,
        FLAVOR,
        TOTAL_ORDER
    FROM (
        SELECT A.FLAVOR, A.TOTAL_ORDER + B.TOTAL_ORDER AS TOTAL_ORDER
        FROM (
            SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
            FROM FIRST_HALF
            GROUP BY FLAVOR) A
        LEFT JOIN (
            SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
            FROM JULY 
            GROUP BY FLAVOR) B ON A.FLAVOR = B.FLAVOR
        ORDER BY TOTAL_ORDER DESC
        ) A
    ) A
WHERE ROWNUM <= 3